### ISSUE TITLE
Any plans for making the add-on work on Windows 11 64-bit?

### ISSUE THREAD

**Issue by julscloudops** [maybites/blender.script.spout#21] opened 2023-01-26 00:48 UTC
Hello maybites, hope you are doing well.

Are there any plans for making this add-on work on Windows 11 64-bit? Does the problem itself have to do with SpoutGL python library?

I am willing to help if it's possible to get me to speed on what's required to accomplish that. 

Best regards.

**Comment by maybites** [comment] 2023-01-26 08:28
It should work. At the time of writing windows 11 wasn't out there. Let me know if it works, I will correct the readme asap.

**Comment by julscloudops** [comment] 2023-02-03 01:02
I was able to install it successfully but it doesn't seem to be sending out the texture to Spout Demo Receiver nor TouchDesigner. I disabled and reenabled the add-on and I checked the Streaming Texture box. Any ideas if I am missing something?

![image](https://user-images.githubusercontent.com/47393182/216485827-e6dd7c13-48a1-40a5-952a-03cffe1b1fca.png)

**Comment by maybites** [comment] 2023-02-03 20:26
what does the console say? (memu > window > toggle window console...)

**Comment by julscloudops** [comment] 2023-02-07 04:05
This was the original issue on the console.

![image](https://user-images.githubusercontent.com/47393182/217146112-9931a930-9f1d-4d5e-baa5-284844b49a6b.png)

I installed the spout package using the python script inside of Blender from this page: https://b3d.interplanety.org/en/installing-python-packages-with-pip-in-blender-on-windows-10/

Then I ran into this issue again after installing the spout package

```
DEPRECATION: spout is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for spout ... done
Successfully installed certifi-2022.12.7 charset-normalizer-3.0.1 idna-3.4 oauthlib-3.2.2 requests-2.28.2 requests-oauthlib-1.3.1 spout-0.1.6 twython-3.9.1 urllib3-1.26.14
FINISHED
Traceback (most recent call last):
  File "C:\Users\jcamp\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\spout-master\operators.py", line 106, in texshare_main
    spyphonSender = FrameBufferSharingServer.create(context.camera.name)
NameError: name 'FrameBufferSharingServer' is not defined
File "C:\Users\jcamp\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\spout-master\operators.py", line 87, in texshare_main
```

Any ideas how to fix this one?

**Comment by maybites** [comment] 2023-02-07 13:37
I cant reproduce.

please try this new release and report back: https://github.com/maybites/blender.script.spout/releases/tag/V3.1.0

**Comment by maybites** [comment] 2023-05-02 12:49
should be fixed with https://github.com/maybites/blender.script.spout/commit/51dbf1d5cdebf71d8e7fc0ba3fee0173377c7645

**Closed as completed by maybites** 2023-05-02 12:49 UTC
